---
apache_configs:
  fqdn: /vagrant/automation/templates/fqdn.conf.j2
apache_mods:
  - rewrite
apache_sites:
  workshop: /vagrant/automation/templates/workshop.conf.j2

mysql_databases:
  - php_workshop
mysql_users:
  - username: 'workshop'
    password: 'workshop'
    privs:
      - '*.*:ALL,GRANT'
    hosts:
      - '%'
      - 'localhost'

samba_shares:
  - name: www
    path: /var/www
samba_users:
  - username: vagrant
    password: vagrant

athena_ssh_key: /vagrant/automation/files/private/id_rsa_demo

deploy_ssh_key: /vagrant/automation/files/private/id_rsa_demo
deploy_git_ssh: git@github.com:horatiubrinza/workshop-php.git
deploy_dest: /var/www/workshop
deploy_hook: /vagrant/automation/hooks/dev/deploy.yml
