---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ _deploy_packages }}"

- name: Ensure ssh folder exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Copy private ssh key
  copy:
    src: /vagrant/{{ deploy_ssh_key }}
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: Ensure deploy folder exists
  file:
    path: "{{ deploy_path }}"
    state: directory
  notify: permissions-apache

- name: Clone repository
  git:
    repo: git@github.com:alexandrubau/workshop-php.git
    dest: "{{ deploy_path }}"
    version: master
    force: yes
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_path }}"

- name: Scanning for sql files
  find:
    paths: "{{ deploy_path }}/sql"
    patterns: '*.sql'
    recurse: yes
  register: _deploy_sql_scripts

- name: Run sql scripts
  shell: mysql < {{ item.path }}
  with_items: "{{ _deploy_sql_scripts.files }}"

- name: Copy app config
  copy:
    src: "{{ deploy_path }}/config/settings-dist.yml"
    dest: "{{ deploy_path }}/config/settings.yml"
  notify: permissions-apache